---
name: Unit Tests

# yamllint disable-line rule:truthy
on:
  workflow_run:
    workflows:
      - Lint
    types:
      - completed
jobs:
  test:
    name: Perform Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.20.0'

      - name: Install Go dependencies
        run: |
          go install github.com/google/go-jsonnet/cmd/jsonnet@latest

      - name: Running Tests
        run: make ci-tests
